minecraft_dependency=1.20.1
minecraft_version=1.20.1

# https://fabricmc.net/develop/
fabric_version=0.92.0+1.20.1

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.16.3
tweakeroo=0.17.1
litematica=0.15.4

#https://modrinth.com/mod/modmenu/versions
modmenu=7.2.2

#https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4592296
kyrptconfig=1.5.4-1.20

