minecraft_dependency=1.19.4
minecraft_version=1.19.4

# https://fabricmc.net/develop/
fabric_version=0.87.2+1.19.4

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.15.4
tweakeroo=0.16.0
litematica=0.14.7

# https://modrinth.com/mod/modmenu/versions
modmenu=6.3.1

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4592290
kyrptconfig=1.5.2-1.19.4


