org.gradle.jvmargs=-Xmx6G
org.gradle.java.installations.auto-detect=true

mod_archives_base_name=litematica-printer
mod_description=Litematica Printer mulit version pack
mod_homepage=https://space.bilibili.com/2093657
mod_id=litematica-printer
mod_wrapper_id=litematica-printer-wrapper
mod_license=AGPL-3.0
mod_maven_group=com.k1nse.litematica-printer
mod_name=Litematica Printer
mod_sources=https://github.com/K1nse-91/litematica-Printer
mod_version=0.4.2.9-K1nse_

loader_version=0.19.1
pinyin_version=2.5.1

# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok_version=1.18.42
