minecraft_dependency=1.20.6
minecraft_version=1.20.6

# https://fabricmc.net/develop/
fabric_version=0.99.4+1.20.6

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.19.2
tweakeroo=0.20.0
litematica=0.18.3

# https://modrinth.com/mod/modmenu/versions
modmenu=10.0.0

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quickshulker=https://github.com/Haocen2004/quickshulker/releases/download/1.20.6-1.4.3/quickshulker-1.4.3-1.20.6.jar
kyrptconfig=1.5.4-1.20


