minecraft_dependency=>=26.2
minecraft_version=26.2

# https://fabricmc.net/develop/
fabric_version=0.152.2+26.2
loader_version=0.19.3

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.29.0
litematica=0.28.3
tweakeroo=0.29.0

# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=20.0.0-beta.3

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.5/quickshulker-v3.2.5-mc26.2-a7aa281-release.jar

# Their integration is temporarily excluded for MC >= 260200 in source and Gradle.

# https://modrinth.com/mod/modmenu/versions
