minecraft_dependency=1.18.2
minecraft_version=1.18.2

# https://fabricmc.net/develop/
fabric_version=0.77.0+1.18.2

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.12.3-alpha.1
tweakeroo=0.13.3
litematica=0.11.7

#https://modrinth.com/mod/modmenu/versions
modmenu=3.2.5

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4008786
kyrptconfig=1.4.6-1.18

